Shop/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data;
using Shop.Data.Services;
using Shop.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class AuthorsController : Controller
    {

        private readonly IAuthorsService _service;

        public AuthorsController(IAuthorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }


        //Get: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Biography")]Author author)
        {
            if(!ModelState.IsValid)            
                return View(author);            

            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //GET: Authors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);

            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        //Get: Authors/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Biography")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }

            await _service.UpdateAsync(id,author);
            return RedirectToAction(nameof(Index));
        }

        //Get: Authors/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Services;
using Shop.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class GamesController : Controller
    {
        private readonly IGamesService _service;

        public GamesController(IGamesService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allGames = await _service.GetAllAsync(n => n.GameShops);
            return View(allGames);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allGames = await _service.GetAllAsync(n => n.GameShops);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allGames.Where(n => n.FullName.Contains(searchString) || n.Descritpion.Contains(searchString)).ToList();
                return View("Index", filteredResult);
            }
            return View("Index", allGames);
        }

        //GET: Authors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var gameDetails = await _service.GetGamesByIdAsync(id);
            return View(gameDetails);
        }

        //Get: Games/Create
        public async Task<IActionResult> Create()
        {
            var gameDropdownData = await _service.GetNewGameDropdownsValues();

            ViewBag.Producers = new SelectList(gameDropdownData.Producers, "Id", "FullName");
            ViewBag.Authors = new SelectList(gameDropdownData.Authors, "Id", "FullName");
            ViewBag.GameShops = new SelectList(gameDropdownData.GameShops, "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewGame game)
        {
            if (!ModelState.IsValid)
            {
                var gameDropdownData = await _service.GetNewGameDropdownsValues();

                ViewBag.Producers = new SelectList(gameDropdownData.Producers, "Id", "FullName");
                ViewBag.Authors = new SelectList(gameDropdownData.Authors, "Id", "FullName");
                ViewBag.GameShops = new SelectList(gameDropdownData.GameShops, "Id", "Name");

                return View(game);
            }

            await _service.AddNewGameAsync(game);
            return RedirectToAction(nameof(Index));
        }


        //Get: Games/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var gameDetails = await _service.GetGamesByIdAsync(id);
            if (gameDetails == null) return View("NotFound");

            var response = new NewGame()
            {
                Id = gameDetails.Id,
                FullName = gameDetails.FullName,
                Descritpion = gameDetails.Descritpion,
                Price = gameDetails.Price,
                ImageURL = gameDetails.ImageURL,
                CreateDate = gameDetails.CreateDate,
                GameCategory = gameDetails.GameCategory,
                AuthorsId = gameDetails.AuthorsId,
                GameShopsId = gameDetails.GameShopsId,
                ProducersId = gameDetails.ProducersId
            };

            var gameDropdownData = await _service.GetNewGameDropdownsValues();

            ViewBag.Producers = new SelectList(gameDropdownData.Producers, "Id", "FullName");
            ViewBag.Authors = new SelectList(gameDropdownData.Authors, "Id", "FullName");
            ViewBag.GameShops = new SelectList(gameDropdownData.GameShops, "Id", "Name");

            return View(response);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewGame game)
        {
            if (id != game.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var gameDropdownData = await _service.GetNewGameDropdownsValues();

                ViewBag.Producers = new SelectList(gameDropdownData.Producers, "Id", "FullName");
                ViewBag.Authors = new SelectList(gameDropdownData.Authors, "Id", "FullName");
                ViewBag.GameShops = new SelectList(gameDropdownData.GameShops, "Id", "Name");

                return View(game);
            }

            await _service.UpdateGameAsync(game);
            return RedirectToAction(nameof(Index));
        }

        //Get: games/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var gamesDetails = await _service.GetByIdAsync(id);

            if (gamesDetails == null) return View("NotFound");
            return View(gamesDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var gamesDetails = await _service.GetByIdAsync(id);
            if (gamesDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shop.Data;
using Shop.Data.Services;
using Shop.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ProducersController : Controller
    {

        private readonly IProducersService _service;

        public ProducersController(IProducersService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }

        //GET: producers/details
        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Description")] Producer producer)
        {
            if (!ModelState.IsValid)            
                return View(producer);            

            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //Get: producers/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Description")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            await _service.UpdateAsync(id, producer);
            return RedirectToAction(nameof(Index));
        }

        //Get: producers/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");
            return View(producerDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Shop/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-black-50-info">404 Not Found</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Games" asp-action="Index">Go Back</a>
    </div>
</div>

Shop/Views/Shared/_CreateItem.cshtml
@model string;


    <div style="position: fixed; z-index: 1; right:25px; bottom: 65px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success float-right">
            <i class="bi bi-plus-circle"></i>Add New
        </a>
    </div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Games" asp-action="Index">Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flax-grow-1">
                            <a class="nav-link text-dark" asp-controller="Games" asp-action="Index"> <i class="bi bi-dice-5"><span style="padding: 5px"></span></i>Games</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Authors" asp-action="Index"><i class="bi bi-file-code"></i> Authors</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-journal-code"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="GameShops" asp-action="Index"><i class="bi bi-journal-code"></i> Shops</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="menu-up"></i> Menu
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Authors" asp-action="Index"><i class="bi bi-file-code"></i> Authors</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-journal-code"></i> Producers</a>
                                    <a class="dropdown-item" asp-controller="GameShops" asp-action="Index"><i class="bi bi-journal-code"></i> Shops</a>
                                </div>
                            </li>
                        }
                    </ul>
                     <form class="form-inline my-2 my-lg-0" asp-controller="Games" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a game..." aria-label="Recipient's username" aria-describedby="button-addon2" \>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                   

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="text-center" >
            &copy; 2022 - GameShop Designed and created By Adam Adamczyk
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>